# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0.0)),
                ('precio_unitario', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.CharField(max_length=100)),
                ('cantidad', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50)),
                ('coeficiente', models.FloatField(default=1.0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('mod_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('observaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numeracion', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio_unitario', models.FloatField(default=0.0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGOapp.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Subrubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGOapp.Rubro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('caracter', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subitem',
            name='tipo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGOapp.TipoItem'),
        ),
        migrations.AddField(
            model_name='subitem',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGOapp.Unidad'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='receptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SGOapp.Receptor'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='subrubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGOapp.Subrubro'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGOapp.Unidad'),
        ),
        migrations.AddField(
            model_name='detallesubitem',
            name='sub_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SGOapp.SubItem'),
        ),
    ]
