# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SGOapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesubitem',
            name='obra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='SGOapp.Obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimiento',
            name='detalle_sub_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='SGOapp.DetalleSubItem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallesubitem',
            name='sub_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SGOapp.SubItem'),
        ),
    ]
