# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SGOapp', '0002_auto_20170827_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='mod_usuario',
        ),
    ]
